### ISSUE TITLE
Xcode 10.2

### ISSUE THREAD

**Issue by DanijelHuis** [taketo1024/SwiftyMath#10]
Hi, just reporting that SwiftyMath code fails to compile in Xcode 10.2. 

Main culprit seems to be this:
https://developer.apple.com/documentation/swift/int/3127690-zero
Xcode 10.2 introduces Int.zero and your library is adding same property via protocol.

Thank you!

**Comment by taketo1024** [comment]
Thanks for reporting, I'll look into it.
