### ISSUE TITLE
not an issue - fyi - sympy + swift tensorflow / python

### ISSUE THREAD

**Issue by johndpope** [taketo1024/SwiftyMath#9]
Perhaps you're aware that google has made some inroads to using python with swift 
https://github.com/tensorflow/swift

(there's a few gotchas for getting up and running)
https://github.com/tensorflow/swift/blob/master/Usage.md

you can see sklearn working here -> 
<img width="1438" alt="screen shot 2018-09-14 at 9 44 46 pm" src="https://user-images.githubusercontent.com/289994/45581168-6f1b4300-b867-11e8-8ab1-cfd9d28d72c2.png">

I'm wanting to port some python code which is using sympy to do symbolic calculus   / like this
https://github.com/johndpope/Symbolic-computation-Python/blob/master/SymPy_Calculus.ipynb
(why? I'm just wanting to help calculate derivatives in xcode with swift - maybe cherry pick ideas and port over to create  a native symbolic mathematics swift library )

To dive into sympy - > 
there's a very simple neural net mnist here - 
https://github.com/Sheyne/Neural/blob/1b0563a65480448a48b395f74a70a7d949112f42/sympy_test.py

some example symbolic code - 
```python

t = sympy.Symbol("t")
y = sympy.Symbol("y")

sigmoid = 1/(1+sympy.exp(-y))
cross_entropy = y * sympy.ln(t)+(1 - y) * sympy.ln(1 - t)
cost =  (y - t) ** 2 / 2
cost_f = sympy.lambdify((y, t), cost, "numpy")
cost_p = sympy.diff(cost, y)
cost_p_f = sympy.lambdify((y, t), cost_p, "numpy")

```

My attempt to port to swift
```swift

import Foundation
import Python



class SymPy{
    
    typealias PO = PythonObject
    // Schema > Run > Pre-actions - source activate gymai
    static func importSysPath(){
        let sys = Python.import("sys")
        let  path = "/Users/\(NSUserName())/miniconda2/envs/gymai/lib/python2.7/site-packages/"
        sys.path.append(path)
        
    }
    
    // https://github.com/Sheyne/Neural/blob/1b0563a65480448a48b395f74a70a7d949112f42/sympy_test.py
    static func run(){
             importSysPath()
        
        let sympy = Python.import("sympy")
        let np = Python.import("numpy")
        //let mpmath = Python.import("mpmath")
        
        let t = sympy.Symbol("t")
        let y = sympy.Symbol("y")
        
        let sigmoid = 1/(1+sympy.exp(-y))
        let cross_entropy = y * sympy.ln(t)+(1 - y) * sympy.ln(1 - t)
        let cost =  sympy.Pow((y - t),2) / 2
        let arr = [y, t]
        let costFunc = sympy.lambdify(arr, cost, ["numpy","numpy"])
        let costP = sympy.diff(cost, y)
        let costPf = sympy.lambdify([y, t], costP, ["numpy","numpy"])
        print("costPF:",costP)
    }
}

```

I made some notes here on setting environment
https://github.com/johndpope/SwiftReinforce

**Comment by Sajjon** [comment]
@johndpope I've created a pure Swift lib for multi-variable partial derivatives, I call it [EquationKit](https://github.com/Sajjon/EquationKit)

@taketo1024 Your library looks great btw!
